name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    container:
      image: adoptopenjdk:11-jdk-hotspot-focal
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/jdks
            ~/.gradle/native
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew publish --no-daemon --stacktrace
        env:
          ORG_GRADLE_PROJECT_wavJfrogUsername: ${{ secrets.DEPLOY_USER }}
          ORG_GRADLE_PROJECT_wavJfrogPassword: ${{ secrets.DEPLOY_PASS }}
